"""Add user_prompt and ai_response to routes

Revision ID: 0d709e09b552
Revises: 46915cff2109
Create Date: 2026-06-07 16:10:14.865132+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d709e09b552'
down_revision: Union[str, None] = '46915cff2109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('user_prompt', sa.String(), nullable=True))
    op.add_column('routes', sa.Column('ai_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'ai_response')
    op.drop_column('routes', 'user_prompt')
    # ### end Alembic commands ###
